/**
 * @file murasaki_platform.hpp
 *
 * @date 2017/11/12
 * @author takemasa
 * @brief An interface for the applicaiton from murasaki library to main.c
 * @details
 * The resources below are impremented in the murasaki_platform.cpp and serve as glue to the main.c.
 */

#ifndef MURASAKI_PLATFORM_HPP_
#define MURASAKI_PLATFORM_HPP_

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
// Murasaki platform control
/**
 * @brief Initialize the platform variables.
 * @ingroup MURASAKI_PLATFORM_GROUP
 * @details
 * The murasaki::platform variable is an interface between the application program and HAL / RTOS.
 * To use it correctly, the initialization is needed before any activity of murasaki client.
 *
 * @code
 * void StartDefaultTask(void const * argument)
 * {
 *     InitPlatform();
 *     ExecPlatform();
 * }
 * @endcode
 *
 * This function have to be invoked from the StartDefaultTask() of the main.c only once
 * to initialize the platform varaiable.
 *
 */
void InitPlatform();

/**
 * @brief The body of the real application.
 * @ingroup MURASAKI_PLATFORM_GROUP
 * @details
 * The body function of the murasaki application. Usually this function is called from
 * the StartDefaultTask() of the main.c.
 *
 * This function is invoked only once, and never return. See @ref InitPlatform() as calling sample.
 *
 * By default, it toggles LED as sample program.
 * Inside this function can be customized freely.
 */

void ExecPlatform();
/**
 * @brief Hook for the assert_failure() in main.c
 * @ingroup MURASAKI_PLATFORM_GROUP
 * @param file Name of the source file where assertion happen
 * @param line Number of the line where assertion happen
 * @details
 * This routine provides a custom hook for the assertion inside STM32 HAL.
 * All assertion raised in HAL will be redirected here.
 *
 * @code
 * void assert_failed(uint8_t* file, uint32_t line)
 * {
 *     CustomAssertFailed(file, line);
 * }
 * @endcode
 * By default, this routine output a message with location informaiton
 * to the debugger console.
 */

void CustomAssertFailed(uint8_t* file, uint32_t line);
/**
 * @brief Hook for the default exception handler. Never return.
 * @ingroup MURASAKI_PLATFORM_GROUP
 * @details
 * This routine is invoked from the default handler of the start up file.
 * The modification to the startup file is user's responsibility.
 *
 * For example, the start up code for the Nucleo-L152RE is startup_stml152xe.s.
 * This file is generated by CubeMX. This file has default handler as like this:
 *
 * @code
 * .section .text.Default_Handler,"ax",%progbits
 *     Default_Handler:
 * Infinite_Loop:
 *     b Infinite_Loop
 * @endcode
 *
 * This code can be modified to call CustomDefaultHanler as like this :
 * @code
 * .global CustomDefaultHandler
 * .section .text.Default_Handler,"ax",%progbits
 * Default_Handler:
 *     bl CustomDefaultHandler
 * Infinite_Loop:
 *     b Infinite_Loop
 * @endcode
 */
void CustomDefaultHandler();
#ifdef __cplusplus
}
#endif


#endif /* MURASAKI_PLATFORM_HPP_ */
